### ISSUE TITLE
能不能增加一个分组功能.

### ISSUE THREAD

**Issue by ffsfwnuiaww** [YDHCUI/manjusaka#16]
太多不同资产上线 牛屎花 之后 及其混乱,,,,尤其是hw打点不同资产的时候 会遇到多个资产。同时上线同一个牛市话,,,,,,,,效果极其爆炸.

所以能不能增加一个上线机子的资产分类功能 或者备注也行

**Comment by YDHCUI** [comment]
0.9 新增 备注功能
