### ISSUE TITLE
linux无法修改心跳会连时间

### ISSUE THREAD

**Issue by Emmp7y** [YDHCUI/manjusaka#21]

**Comment by YDHCUI** [comment]
网页界面上面显示的心跳时间是npu的推送间隔时间 默认是60s。实际的npc心跳时间默认大约3s， 如果修改的话会心跳会回显到NPC休眠时间的修改框里面。

这样做的目的是缓解npu的推送的压力，前面几个版本是直接根据回连时间来做推送的， 但是这样 如果npc一多的话 会造成界面卡死。
