### ISSUE TITLE
文件编辑不支持中文编码。 并且点击保存 或者上线 会无限弹窗

### ISSUE THREAD

**Issue by Emmp7y** [YDHCUI/manjusaka#22]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/89745506/235493834-f4454cf0-15b1-40e9-8372-81cdd02ad0d8.png">
<img width="326" alt="image" src="https://user-images.githubusercontent.com/89745506/235493984-6a64ca63-b237-45b9-bd63-50f477b24ad8.png">

**Comment by YDHCUI** [comment]
已更新
