### ISSUE TITLE
an inexplicable error

### ISSUE THREAD

**Issue by condesings** [YDHCUI/manjusaka#8]
#sh "ls -al"
-al": -c:行0: 寻找匹配的 `"' 是遇到了未预期的文件结束符
-al": -c:行1: 语法错误: 未预期的文件结尾

**Comment by YDHCUI** [comment]
这个错误我没有复现，不过我估计是因为 没有加路径的原因 你试试 sh ls -al /

**Comment by condesings** [comment]
噢噢 谢谢

**Comment by condesings** [comment]
命令行终端不能执行加参数的命令 比如 ls -al。他只是执行了ls命令。

**Comment by YDHCUI** [comment]
0.6已修复。。
