### ISSUE TITLE
Can't find password, and no help command, don't know what i'm doing wrong............ 找不到密码，也没有帮助命令，不知道我在做什么错

### ISSUE THREAD

**Issue by pentest01** [YDHCUI/manjusaka#9]
no password included. and the default password on the web ui isn't logging in

![Screenshot_2022-11-09_11_02_12](https://user-images.githubusercontent.com/103268912/201441401-069b6a07-eaac-495b-9efb-4d9187bf7ea6.png)

![Screenshot_2022-11-11_17_57_42](https://user-images.githubusercontent.com/103268912/201441929-150fc5dd-fcec-42af-947a-803e9ce179a5.png)

![Screenshot_2022-11-11_17_58_07](https://user-images.githubusercontent.com/103268912/201441948-00d3292e-9096-4378-83c2-bf532c3de099.png)

**Comment by YDHCUI** [comment]
密码在你首次运行 manjusaka时自动生成，如果你忘记了 可以在同目录下的 nps.db 里面修改 或者直接删除nps.db 重新生成新密码

**Comment by pentest01** [comment]
Generating payload redirect to microsoft.com


![image](https://user-images.githubusercontent.com/103268912/202860916-d8ec1381-1a9d-4bc7-8583-e39aec6e7f94.png)
